version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - mauran
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: symfony/maker-bundle
    versions:
    - 1.28.0
    - 1.29.0
    - 1.29.1
    - 1.30.0
    - 1.30.1
  - dependency-name: symfony/flex
    versions:
    - 1.11.0
    - 1.12.1
